package com.rmdc.ontologyEditor.model;
// Generated Oct 22, 2017 4:41:35 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * ChangeInstances generated by hbm2java
 */
@Entity
@Table(name="change_instances"
    ,catalog="ontologyeditor"
)
public class ChangeInstances  implements java.io.Serializable {

     @Id @GeneratedValue(strategy= GenerationType.AUTO)
     private Integer id;
     @ManyToOne(fetch=FetchType.LAZY)
     private OntoChange ontoChange;
     private byte[] object;
     private String description;

    public ChangeInstances() {
    }

    public ChangeInstances(OntoChange ontoChange, byte[] object, String description) {
       this.ontoChange = ontoChange;
       this.object = object;
       this.description = description;
    }



    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    @JoinColumn(name="onto_change_id", nullable=false)
    public OntoChange getOntoChange() {
        return this.ontoChange;
    }
    
    public void setOntoChange(OntoChange ontoChange) {
        this.ontoChange = ontoChange;
    }

    
    @Column(name="object", nullable=false)
    public byte[] getObject() {
        return this.object;
    }
    
    public void setObject(byte[] object) {
        this.object = object;
    }

    
    @Column(name="description", nullable=false, length=120)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


