package com.rmdc.ontologyEditor.model;
// Generated Oct 22, 2017 4:41:35 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ChangeType generated by hbm2java
 */
@Entity
@Table(name="change_type"
    ,catalog="ontologyeditor"
)
public class ChangeType implements java.io.Serializable {

    @Id @GeneratedValue(strategy= GenerationType.AUTO)
     private Integer id;
     private String description;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="changeType")
     private Set<OntoChange> ontoChanges = new HashSet(0);

    public ChangeType() {
    }

    public ChangeType(String description, Set ontoChanges) {
       this.description = description;
       this.ontoChanges = ontoChanges;
    }

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set<OntoChange> getOntoChanges() {
        return this.ontoChanges;
    }
    
    public void setOntoChanges(Set<OntoChange> ontoChanges) {
        this.ontoChanges = ontoChanges;
    }




}


