package com.rmdc.ontologyEditor.model;
// Generated Oct 22, 2017 4:41:35 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="ontologyeditor"
)
public class User  implements java.io.Serializable {

    @Id @GeneratedValue(strategy= GenerationType.AUTO)
     private Integer id;
     private Date timestamp;
     @ManyToOne(fetch=FetchType.LAZY)
     private Role role;
     private String name;

     private String password;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
     private Set<OntoChange> ontoChanges= new HashSet(0);
     @ManyToMany(fetch=FetchType.LAZY)
     private Set<OntoVersion> ontoVersions = new HashSet(0);

    public User() {
    }

	
    public User(Role role, String name, String password) {
        this.role = role;
        this.name = name;
        this.password = password;
    }
    public User(Role role, String name, String password, Set ontoChanges, Set ontoVersions) {
       this.role = role;
       this.name = name;
       this.password = password;
       this.ontoChanges = ontoChanges;
       this.ontoVersions = ontoVersions;
    }
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestamp", length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Set<OntoChange> getOntoChanges() {
        return this.ontoChanges;
    }
    
    public void setOntoChanges(Set<OntoChange> ontoChanges) {
        this.ontoChanges = ontoChanges;
    }


    @JoinTable(name="version_user_assignment", catalog="ontologyeditor", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="onto_version_id", nullable=false, updatable=false) })
    public Set<OntoVersion> getOntoVersions() {
        return this.ontoVersions;
    }
    
    public void setOntoVersions(Set<OntoVersion> ontoVersions) {
        this.ontoVersions = ontoVersions;
    }


}


